force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Technical object, storing application logs and errors.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Apex Class Name.</description>
    <inlineHelpText>Apex Class Name.</inlineHelpText>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Context (ID or Timestamp).</description>
    <inlineHelpText>Context (ID or Timestamp).</inlineHelpText>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <description>Line number in the Apex Class.</description>
    <inlineHelpText>Line number in the Apex Class.</inlineHelpText>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Error Message or Description</description>
    <inlineHelpText>Error Message or Description</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Apex Method Name.</description>
    <inlineHelpText>Apex Method Name.</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Log.cls
/**
Logging utility. Derived from https://github.com/rsoesemann/apex-unified-logging
**/

public with sharing class Log {

    private static final String ORG_NAMESPACE = [SELECT NamespacePrefix FROM Organization LIMIT 1].NamespacePrefix;
    private static final String CLASSNAME = Log.class.getName();
    private static final Pattern STACK_LINE = Pattern.compile('^(?:Class\\.)?([^.]+)\\.?([^\\.\\:]+)?[\\.\\:]?([^\\.\\:]*): line (\\d+), column (\\d+)$');
    private static final String DEFAULT_CONTEXT = timestamp();


    /**
    * @description: Logs a simple error
    * @params: message (short description of the error)
    * @return: void
    */
    public static void error(String message) {
        error(message, new List<Object>(), null);
    }

    /**
    * @description: Logs an error with a list of associated information
    * @params: message (short description of the error)
    * @params: values (list of objects containing additional information about the error)
    * @return: void
    */
    public static void error(String message, List<Object> values) {
        error(message, values, null);
    }

    /**
    * @description: Logs an error associated to a record or job ID
    * @params: message (short description of the error)
    * @params: contextId (ID of the associated record or job)
    * @return: void
    */
    public static void error(String message, Id contextId) {
        error(message, new List<Object>(), contextId);
    }

    /**
    * @description: Logs an error associated to a record or job ID, with a list of associated information
    * @params: message (short description of the error)
    * @params: values (list of objects containing additional information about the error)
    * @params: contextId (ID of the associated record or job)
    * @return: void
    */
    public static void error(String message, List<Object> values, Id contextId) {
        insertLog(message, values, contextId);
    }



    private static void insertLog(String message, List<Object> values, Id contextId) {
        message = message +' ; '+ cast(values);
        System.debug('message ' + message);
        try{
            Log__c newLog = new Log__c(Message__c = message);
            newLog.Context__c = (contextId == null) ? DEFAULT_CONTEXT : ' '+contextId;
            populateLocation(newLog);
            insert(newLog);
        }
        catch (exception err){
            System.debug(err);
        }
    }


    private static List<String> cast(List<Object> values) {
        List<String> result = new List<String>();
        for(Object value : values) {
            System.debug('value: '+value);
            result.add(' ' + value);
        }
        System.debug('result: '+result);
        return result;
    }


    private static String timestamp() {
        return System.now().formatGmt('HH:mm:ss.SSS');
    }


    private static void populateLocation(Log__c logMessage) {
        // Note: Idea taken from https://salesforce.stackexchange.com/questions/153835
        List<String> stacktrace = new DmlException().getStackTraceString().split('\n');

        for(String line : stacktrace) {
            Matcher matcher = STACK_LINE.matcher(line);
            if(matcher.find() && !line.startsWith('Class.' + CLASSNAME + '.')) {
                logMessage.Class__c = matcher.group(1);
                logMessage.Method__c = prettyMethod(matcher.group(2));
                logMessage.Line__c = Integer.valueOf(matcher.group(4));
                return;
            }

        }
    }


    private static String prettyMethod(String method) {
        String result = (method == null) ? 'anonymous' : method;
        return (result.contains('init')) ? 'ctor' : result;
    }

}